version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install aws-cdk-lib constructs

  build:
    commands:
      - echo "Synthesizing the CDK app..."
      - npx cdk synth
      - echo "Deploying the stack..."
      - npx cdk deploy CdkProjectStack --require-approval never

      


artifacts:
  files:
    - '**/*'
